"use client";
import React, { useState } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { content } from '../translations';

const TermsAndConditions = () => {
  const [language, setLanguage] = useState<'en' | 'hi'>('en');
  const t = content[language];

  return (
    <div className={`bg-white min-h-screen ${language === 'hi' ? 'font-hindi' : ''}`}>
      <Navbar t={t.nav} language={language} setLanguage={setLanguage} />

      <main className="pt-32 pb-20">
        <div className="max-w-4xl mx-auto px-6 lg:px-8">
          
          <div className="mb-12 border-b border-slate-100 pb-10 text-left">
            <h1 className="text-4xl font-bold text-slate-900 mb-4 tracking-tight">Terms and Conditions</h1>
            <p className="text-slate-500 text-sm leading-relaxed text-justify">
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </div>

          <div className="space-y-10 text-slate-700 leading-relaxed text-justify">
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">1. Ownership and Domain</h2>
              <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://lyss.in" className="text-purple-700 font-medium hover:underline">https://lyss.in</a> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform'). The Platform is owned by <strong>LYSS TECHNOLOGY PRIVATE LIMITED</strong>, a company incorporated under the Companies Act, 1956 with its registered office at H No 3 365 Lakho Binda Campus, Santu Nagar, Madhubani, Bihar (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">2. Agreement to Terms</h2>
              <p>
                Your use of the Platform and services and tools are governed by the following terms and conditions ('Terms of Use'). By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms proposed by You which conflict with these Terms of Use are expressly rejected by the Platform Owner.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">3. User Obligations and Registration</h2>
              <p>
                To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account. Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered for any specific purpose. You acknowledge that such information may contain inaccuracies or errors and we expressly exclude liability for such to the fullest extent permitted by law.
              </p>
            </section>

            <section className="bg-slate-50 p-6 rounded-xl border border-slate-200">
              <h2 className="text-xl font-bold text-slate-900 mb-4 text-left">4. Proprietary Rights and Use</h2>
              <p className="mb-4">
                The contents of the Platform and the Services are proprietary to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents, which includes but is not limited to the design, layout, look, and graphics. Your use of our Services is solely at your own risk and discretion, for which we shall not be liable. It is your responsibility to ensure that the Services meet your specific requirements.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">5. Prohibited Activities</h2>
              <p>
                You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws. Unauthorized use of the Platform may lead to action against you as per these Terms of Use and/or applicable laws. You agree to pay us the charges associated with availing the Services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">6. Indemnity and Liability</h2>
              <p>
                You shall indemnify and hold harmless Platform Owner, its affiliates, and their respective officers from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, Privacy Policy, or Your violation of any law. Notwithstanding anything contained, the parties shall not be liable for any failure to perform an obligation if prevented or delayed by a force majeure event.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">7. Third-Party Links</h2>
              <p>
                The Platform may contain links to third-party websites. On accessing these links, you will be governed by the terms of use and privacy policy of such third-party websites. These links are provided for your convenience for providing further information.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-3 text-left">8. Governing Law and Jurisdiction</h2>
              <p>
                These Terms and any dispute relating to it shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <strong>Madhubani and Bihar</strong>.
              </p>
            </section>

            {/* Corporate Compliance Card */}
            <section className="mt-16 bg-slate-50 rounded-2xl p-8 border border-slate-200 text-left shadow-sm">
              <h2 className="text-lg font-bold text-purple-900 mb-6 uppercase tracking-wider">Contact & Compliance</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm">
                <div>
                  <p className="text-slate-500 uppercase text-[10px] font-bold mb-1">Entity</p>
                  <p className="text-slate-900 font-semibold text-base mb-4">LYSS Technology Private Limited</p>
                  
                  <p className="text-slate-500 uppercase text-[10px] font-bold mb-1">Grievance / Support</p>
                  <p className="text-slate-900 font-medium">Mr. Atul Kumar (Director)</p>
                </div>
                <div>
                  <p className="text-slate-500 uppercase text-[10px] font-bold mb-1">Registered Address</p>
                  <p className="text-slate-700 leading-relaxed italic">
                    H No 3 365, Lakho Binda Campus,<br/>
                    Santu Nagar, Madhubani,<br/>
                    Bihar - 847211
                  </p>
                  <p className="text-purple-700 font-medium mt-2">support@lyss.in</p>
                </div>
              </div>
            </section>

          </div>
        </div>
      </main>

      <Footer t={t} />
    </div>
  );
};

export default TermsAndConditions;